name: Hello World
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello
        run: echo Hellow, world!
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Bye
        run: echo Good bye!
        needs: [hello]
