name: New Issue
on:
  issues:
    types:
      - opened
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:

      - name: Print Issue Content
        run: |
          echo "New Issue Content:"
          echo "Title: ${{ github.event.issue.title }}"
          echo "Body: ${{ github.event.issue.body }}"
